{
 "title": "Detalhes das OLT",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "estado",
    "label": "Estado",
    "query": {}
   },
   {
    "name": "cidade",
    "label": "Cidade",
    "query": {}
   },
   {
    "name": "bairro",
    "label": "Bairro",
    "query": {}
   },
   {
    "name": "host",
    "label": "OLT",
    "query": {}
   },
   {
    "name": "hardware_name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h2><center>${hardware_name}</center></h2>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SNMP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "SNMP agent availability" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latência",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latência",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "Uptime (network)" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "options": {
    "content": "<center><img src=\"/public/img/icon_clock.png\" alt=\"Battery icon\" width=\"120\" height=\"120\"></center>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Perda de Pacotes",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ONTs: Status Gerais",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:2197",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:2198",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ONT Onlines" ],
       "text": "setAlias(ONT Onlines)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Total ONUs Online/" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:2220",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:2221",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ONT Offlines" ],
       "text": "setAlias(ONT Offlines)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Total ONUs Offline/" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:2243",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:2244",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ONTs Autorizadas" ],
       "text": "setAlias(ONTs Autorizadas)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Total ONUs.*/" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:2266",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ONTs não Autorizadas" ],
       "text": "setAlias(ONTs não Autorizadas)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "Total ONUs Desprovisionadas" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status dos Ramais (Link Status Porta pon)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:3066",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: Interface (.*): Link Status/",
        "$1"
       ],
       "text": "replaceAlias(/$host: Interface (.*): Link Status/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Application: Pon Link Status" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Utilização da CPU",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:3282",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: (.*): Utilization/",
        "$1"
       ],
       "text": "replaceAlias(/$host: (.*): Utilization/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Utilization/" },
     "itemTag": { "filter": "Application: CPU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temperatura das CPUs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:3228",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: (.*): Temperature/",
        "$1"
       ],
       "text": "replaceAlias(/$host: (.*): Temperature/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Temperature/" },
     "itemTag": { "filter": "Application: CPU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "options": {
    "content": "<center><img src=\"/public/img/icon_temperature.png\" alt=\"Temperature icon\" width=\"150\" height=\"150\"></center>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Problems - Real Time",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 2,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<h2><center>ONUs: Network</center></h2>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ONUs AUTORIZADAS por Porta PON",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1622",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: Interface (.*): Ramais/",
        "$1"
       ],
       "text": "replaceAlias(/$host: Interface (.*): Ramais/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Application: Ramais" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "ONUs ONLINE por Porta PON",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:534",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: Interface (.*): Total ONUs Online/",
        "$1"
       ],
       "text": "replaceAlias(/$host: Interface (.*): Total ONUs Online/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Total ONUs Online/" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ONUs OFFLINE por Porta PON",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:966",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: Interface (.*): Total ONUs Offline/",
        "$1"
       ],
       "text": "replaceAlias(/$host: Interface (.*): Total ONUs Offline/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Total ONUs Offline/" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tráfego de Uplink - Ethernet0/8/0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:96",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Upload" ],
       "text": "setAlias(Upload)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Interface ethernet0/8/0(): Bits sent"
     },
     "itemTag": { "filter": "Application: Network" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:117",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Download" ],
       "text": "setAlias(Download)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Interface ethernet0/8/0(): Bits received"
     },
     "itemTag": { "filter": "Application: Network" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tráfego de Rede por Porta PON",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:150",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: Interface (.*): Bits received/",
        "$1"
       ],
       "text": "replaceAlias(/$host: Interface (.*): Bits received/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* GPON .* Bits received$/" },
     "itemTag": { "filter": "Application: Network" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "<h2><center>ONTs: Status</center></h2>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Atenuação da Fibra",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:2077",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/$host: (.*)/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*: Rx Power$/" },
     "itemTag": { "filter": "Application: ONU" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TOP 5 - ONT mais quentes",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:2811",
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "last"
       ],
       "text": "top(5, last)"
      },
      {
       "$$hashKey": "object:2812",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: (.*): Temperature/",
        "$1"
       ],
       "text": "replaceAlias(/$host: (.*): Temperature/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/ONT .* Temperature/" },
     "itemTag": { "filter": "Application: ONU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status das ONTs",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:63",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: (.*): Status/",
        "$1"
       ],
       "text": "replaceAlias(/$host: (.*): Status/, $1)"
      }
     ],
     "group": {
      "filter": "Sintercom/$estado/$cidade/$bairro"
     },
     "host": { "filter": "$host" },
     "item": { "filter": "/ONT .* Status/" },
     "itemTag": { "filter": "Application: ONU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}